### ISSUE TITLE
license doubt about Joshua Morin - On the run

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/songs#4]
The license.txt file says [the song](https://github.com/UltraStar-Deluxe/songs/tree/master/Creative%20Commons/Joshua%20Morin%20-%20On%20the%20run) is http://creativecommons.org/licenses/by-sa/2.5/

But I was not able to find any proof for this on the internet.

Instead, I found the song on commercial music platforms without any hint that it is under Creative Commons.
- https://www.youtube.com/watch?v=kj43v0YXv38
- https://open.spotify.com/intl-de/track/75cSWRcduxaAgVDFdf9pbH
- https://music.apple.com/sg/song/on-the-run/205373158

CC attribution on these platforms is missing and that would violate the Creative Commons license. Thus, I think it is likely that it is not a CC song in the first place.

Is there anyone who can contact the artist or other source of truth that could verify the song's license?
If the answer is no then I suggest to remove the song from this repo.

**Comment by basisbit** [comment]
see https://sourceforge.net/projects/ultrastardx/files/Songs/Joshua%20Morin%20-%20On%20the%20run%20%28CC%20License%20-%20SA%202.5%29/

It is common for songs to be relicensed by astists a couple of times during the life, but if something is creative commons once, it always can be continued to be shared as such.

**Comment by achimmihca** [comment]
> if something is creative commons once, it always can be continued to be shared as such

Makes sense to me.

However, IMHO the old USDX ZIP archive is not a robust evidence that this particular song has been CC in the first place.
Like "it can be part of a CC UltraStar archive because it was part of a CC UltraStar archive"
Sounds like circlular reasoning to me.

**Comment by basisbit** [comment]
I didn't intent to use it as a reason, but instead only wanted to give additional information.

**Comment by achimmihca** [comment]
Ok thanks.
I will close this issue because there seems to be no doubt on your side about the song's license.
